# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-09 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20160906_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msgboard',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
